import numpy as np
import matplotlib.pyplot as plt

class LoveOSGroupDynamics:
    """
    Love-OS Collective Dynamics Engine (Kuramoto-based)
    Simulates synchronization and thermal loss (shame/stress) in a network.
    """
    def __init__(self, N=20, K=1.0, dt=0.01):
        self.N = N
        self.K = K
        self.dt = dt
        # ω (Omega): Intrinsic frequency (Individuality)
        self.omegas = np.random.normal(loc=0.0, scale=1.0, size=N)
        # θ (Theta): Current phase
        self.thetas = np.random.uniform(0, 2*np.pi, size=N)
    
    def step(self):
        """Time evolution step"""
        # Phase difference matrix: theta_j - theta_i
        diff = self.thetas[:, np.newaxis] - self.thetas
        
        # Interaction term: sum(K * sin(diff))
        # Future: Replace K with K_ij matrix for selective coupling
        interaction = (self.K / self.N) * np.sum(np.sin(diff), axis=1)
        
        # Calculate actual velocity
        d_theta = self.omegas + interaction
        
        # Calculate Stress (Heat) generated by forced deviation
        # Stress = (Actual Speed - Natural Speed)^2
        stress_i = (d_theta - self.omegas)**2
        total_stress = np.sum(stress_i)
        
        # Update phases
        self.thetas += d_theta * self.dt
        
        # Calculate Order Parameter (Synchronization Level)
        z = np.sum(np.exp(1j * self.thetas)) / self.N
        order_param = np.abs(z)
        
        return order_param, total_stress

# Usage Example
if __name__ == "__main__":
    sim = LoveOSGroupDynamics(N=50, K=8.0) # High pressure society
    print("Simulating High Pressure Society...")
    for t in range(5):
        r, heat = sim.step()
        print(f"Time {t}: Sync={r:.2f}, Heat={heat:.2f}")
